### PR TITLE
Replace isort, black, pylint with ruff

### PR DESCRIPTION
**Pull request by theferrit32**
Closes https://github.com/clingen-data-model/clinvar-ingest/issues/123

### CODE REVIEW

**Comment by theferrit32** [comment]
Closes #123

**Comment by bpblanken** [comment]
Here's what I got working in `seqr` if you're interested: https://github.com/broadinstitute/seqr-loading-pipelines/blob/main/pyproject.toml#L33-L54

**Comment by theferrit32** [comment]
@bpblanken cool I was looking through the other rule sets. Some of the style ones will be annoying to fix.

**Comment by theferrit32** [comment]
Wild suggestion here
```
clinvar_ingest/api/main.py:7:26: TCH002 Move third-party import `google.cloud.bigquery` into a type-checking block
  |
6 | from fastapi import BackgroundTasks, FastAPI, HTTPException, Request, status
7 | from google.cloud import bigquery
  |                          ^^^^^^^^ TCH002
8 |
9 | import clinvar_ingest.config
  |
  = help: Move into type-checking block
```

It wants to change it to this:
```
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from google.cloud import bigquery
```

**Review by toneillbroad — APPROVED** [review]
Nice work

**Comment by bpblanken** [comment]
@theferrit32  the TYPE_CHECKING thing is normal though it looks crazy.  It's designed to help with circular imports for type annotations.

**Pull request merged**
